apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-skaffold-02
  labels:
    app: spring-skaffold-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-skaffold-02
  template:
    metadata:
      labels:
        app: spring-skaffold-02
    spec:
      containers:
      - name: getting-started
        image: gcr.io/k8s-skaffold/skaffold-example
