apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    docker:
      dockerfile: Dockerfile.bad_idea
deploy:
  kubectl:
    manifests:
      - k8s-*
