apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-skaffold-03
  labels:
    app: quarkus-skaffold-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-skaffold-03
  template:
    metadata:
      labels:
        app: quarkus-skaffold-03
    spec:
      containers:
      - name: getting-started
        image: gcr.io/k8s-skaffold/skaffold-example
