apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    custom:
      buildCommand: ./custom-build.sh
deploy:
  kubectl:
    manifests:
      - k8s-*
